# Generated by Django 5.0.7 on 2024-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
