# Generated by Django 5.0.7 on 2024-07-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_email_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user_id',
        ),
    ]
