# Generated by Django 5.0.7 on 2024-07-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_role_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
